### ISSUE TITLE
Get Elements keyword returning 0 because it does not wait element attached state.

### ISSUE THREAD

**Issue by GavinRodgers-EN0055** [MarketSquare/robotframework-browser#1467]
**Describe the bug**
When searching a webpage for multiple elements of the same type (e.g. checkbox) to use in a random selector we get the error `0 elements of type =checkbox`. But when we us `Get Element` with the same search criteria we get the error `found 3 elements of type checkbox`

**To Reproduce**
1. Search a webpage that has multiple elements/attributes of the same type
2. Using `Get Elements` try to get them to return as a list
3. Get the error `0 elements of type =<what you are searching for>`

**Expected behavior**
This works in version 6.0.0 which was the version we have been using from August until October (upgraded to 10.0.1 on Nov 1st)
Expecting the `Get Elements` keyword to return a list of elements of the given type which will allow us to use these in the further steps of our test e.g. Click a random checkbox from the returned list

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Chrome
 - Version 95.0.4638.54
 - RobotFramework Version 4.1.2

**Additional context**
As we are automating an internal web application I am not able to supply links or snippets of code due to security constraints. But please let me know if there is anything I can add here that could help with this issue

**Comment by aaltat** [comment]
There is 10.0.2 available, which fixes few things related to this issue. Would you be try it and report back. If that doesn't help, could you provide more details about the problem. 

Example which we can also run is the easiest way for us to debug the problem. If that is not possible, could you do the following. 
1) Run tests with --loglevel trace set from command line and show us the full stack trace. 
2) Enable playwright debug logs from library import and show us the relevant parts from the debug file. Please remember that playwright debug log contains everything as plain text, so remove any sensitive information.

**Comment by GavinRodgers-EN0055** [comment]
I will provide stacktace now soon.

Yes tried this with 10.0.2 also and I got the same errors as shown in the main description of the issue.

For context here is the robot code used for what we are trying to do:

```Get Available Elements And Click
    @{elements}=    Get Elements    css=[type="checkbox"]
    ${count}=    Get Length    ${elements}
    ${list}=    Create List
    FOR    ${item}    IN RANGE    0    ${count}
    ${value}=    Browser.Get Property    ${Elements}[${item}]    name
    Run Keyword And Continue On Failure    Browser.Click    css=[name="${value}"]
    END

**Comment by aaltat** [comment]
Could you also try with previous major releases 9.0.2? It would be interesting for compare the results and log files.

**Comment by GavinRodgers-EN0055** [comment]
This was successful in version 9.0.2.

Below is the playwright log from the failure in v10.0.2
```
Playwright Log
robotframework-browser==10.0.2

{"level":30,"time":"2021-11-03T21:28:27.527Z","pid":32333,"hostname":"Host","msg":"Listening on 56173"}
================= Original suppressed error =================
Error: Browser has been closed.
    at PlaywrightState.getActiveBrowser (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:26919:23)
    at PlaywrightServer.getActiveBrowser (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:24881:79)
    at PlaywrightServer.<anonymous> (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:25259:98)
    at step (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:24841:23)
    at Object.next (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:24822:53)
    at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:24816:71
    at new Promise (<anonymous>)
    at __webpack_modules__../node/playwright-wrapper/grpc-service.ts.__awaiter (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:24812:12)
    at PlaywrightServer.__webpack_modules__../node/playwright-wrapper/grpc-service.ts.PlaywrightServer.setTimeout (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:25250:16)
    at handleUnary (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:18454:13)
=============================================================
2021-11-03T21:28:27.576Z pw:api => browserType.launch started
2021-11-03T21:28:31.133Z pw:api <= browserType.launch succeeded
{"level":30,"time":"2021-11-03T21:28:31.144Z","pid":32333,"hostname":"Host","msg":"currentBrowser: [object Object]"}
2021-11-03T21:28:31.159Z pw:api => browser.newContext started
2021-11-03T21:28:31.168Z pw:api <= browser.newContext succeeded
2021-11-03T21:28:31.179Z pw:api => browserContext.addInitScript started
2021-11-03T21:28:31.180Z pw:api <= browserContext.addInitScript succeeded
{"level":30,"time":"2021-11-03T21:28:31.216Z","pid":32333,"hostname":"Host","msg":"Changed active context"}
2021-11-03T21:28:31.217Z pw:api => browserContext.newPage started
2021-11-03T21:28:32.480Z pw:api <= browserContext.newPage succeeded
{"level":30,"time":"2021-11-03T21:28:32.480Z","pid":32333,"hostname":"Host","msg":"Video path: undefined"}
{"level":30,"time":"2021-11-03T21:28:32.480Z","pid":32333,"hostname":"Host","msg":"Changed active page"}
2021-11-03T21:28:32.481Z pw:api => page.goto started
2021-11-03T21:28:32.482Z pw:api navigating to "localhost:4200", waiting until "load"
2021-11-03T21:28:32.513Z pw:api   navigated to "http://localhost:4200/"
2021-11-03T21:28:33.726Z pw:api   navigated to "http://localhost:4200/"
2021-11-03T21:28:33.763Z pw:api   "domcontentloaded" event fired
2021-11-03T21:28:33.968Z pw:api   "domcontentloaded" event fired
2021-11-03T21:28:34.313Z pw:api   "load" event fired
2021-11-03T21:28:34.314Z pw:api <= page.goto succeeded
{"level":30,"time":"2021-11-03T21:28:34.326Z","pid":32333,"hostname":"Host","msg":"Strict mode is enabled, find Locator with css=[aria-label=\"Billing\"] in page."}
2021-11-03T21:28:34.328Z pw:api => locator.click started
2021-11-03T21:28:34.331Z pw:api waiting for selector "css=[aria-label="Billing"]"
2021-11-03T21:28:34.586Z pw:api   navigated to "http://localhost:4200/home"
2021-11-03T21:28:34.598Z pw:api   selector resolved to visible <a aria-hidden="false" aria-label="Billing" _ngcont…>…</a>
2021-11-03T21:28:34.652Z pw:api attempting click action
2021-11-03T21:28:34.652Z pw:api   waiting for element to be visible, enabled and stable
2021-11-03T21:28:34.719Z pw:api   element is visible, enabled and stable
2021-11-03T21:28:34.719Z pw:api   scrolling into view if needed
2021-11-03T21:28:34.721Z pw:api   done scrolling
2021-11-03T21:28:34.722Z pw:api   checking that element receives pointer events at (48,436.78)
2021-11-03T21:28:34.745Z pw:api   element does receive pointer events
2021-11-03T21:28:34.745Z pw:api   performing click action
2021-11-03T21:28:34.837Z pw:api   click action done
2021-11-03T21:28:34.837Z pw:api   waiting for scheduled navigations to finish
2021-11-03T21:28:34.838Z pw:api   navigated to "http://localhost:4200/payments/summary"
2021-11-03T21:28:34.843Z pw:api   navigations have finished
2021-11-03T21:28:34.843Z pw:api <= locator.click succeeded
{"level":30,"time":"2021-11-03T21:28:34.848Z","pid":32333,"hostname":"Host","msg":"Strict mode is enabled, find Locator with css=[class=\"payment-overview-make-payment-button button ng-star-inserted\"] in page."}
2021-11-03T21:28:34.848Z pw:api => locator.click started
2021-11-03T21:28:34.848Z pw:api waiting for selector "css=[class="payment-overview-make-payment-button button ng-star-inserted"]"
2021-11-03T21:28:34.953Z pw:api   selector resolved to visible <a ui-button="" _nghost-omj-c17="" _ngcontent-omj-c…>Make Payment</a>
2021-11-03T21:28:34.958Z pw:api attempting click action
2021-11-03T21:28:34.958Z pw:api   waiting for element to be visible, enabled and stable
2021-11-03T21:28:34.986Z pw:api   element is visible, enabled and stable
2021-11-03T21:28:34.986Z pw:api   scrolling into view if needed
2021-11-03T21:28:34.986Z pw:api   done scrolling
2021-11-03T21:28:34.987Z pw:api   checking that element receives pointer events at (1068.79,152.97)
2021-11-03T21:28:34.989Z pw:api   element does receive pointer events
2021-11-03T21:28:34.989Z pw:api   performing click action
2021-11-03T21:28:35.032Z pw:api   click action done
2021-11-03T21:28:35.032Z pw:api   waiting for scheduled navigations to finish
2021-11-03T21:28:35.032Z pw:api   navigated to "http://localhost:4200/payments/one-time-payment"
2021-11-03T21:28:35.035Z pw:api   navigations have finished
2021-11-03T21:28:35.036Z pw:api <= locator.click succeeded
{"level":30,"time":"2021-11-03T21:28:35.039Z","pid":32333,"hostname":"Host","msg":"Strict mode is enabled, find Locator with css=.one-time-payment-choose-policy-title in page."}
2021-11-03T21:28:35.040Z pw:api => locator.waitFor started
2021-11-03T21:28:35.040Z pw:api waiting for selector "css=.one-time-payment-choose-policy-title" to be visible
2021-11-03T21:28:35.043Z pw:api   selector resolved to visible <h2 _ngcontent-omj-c279="" class="one-time-payment-c…>Make a payment</h2>
2021-11-03T21:28:35.045Z pw:api <= locator.waitFor succeeded
############################################################
# This is where the keyword executes to return 0 elements  #
############################################################
{"level":30,"time":"2021-11-03T21:28:35.049Z","pid":32333,"hostname":"Host","msg":"Strict mode is disbaled, return Locator: css=[type=\"checkbox\"] in page."}
2021-11-03T21:28:35.050Z pw:api => locator.count started
2021-11-03T21:28:35.057Z pw:api <= locator.count succeeded
{"level":30,"time":"2021-11-03T21:28:35.063Z","pid":32333,"hostname":"Host","msg":"Strict mode is enabled, find Locator with xpath=//button[contains(text(),'Next')] in page."}
2021-11-03T21:28:35.064Z pw:api => locator.click started
2021-11-03T21:28:35.064Z pw:api waiting for selector "xpath=//button[contains(text(),'Next')]"
2021-11-03T21:28:35.139Z pw:api   selector resolved to visible <button disabled="true" _nghost-omj-c17="" class="button…> Next </button>
2021-11-03T21:28:35.143Z pw:api attempting click action
2021-11-03T21:28:35.143Z pw:api   waiting for element to be visible, enabled and stable
2021-11-03T21:28:35.170Z pw:api     element is not enabled - waiting...
2021-11-03T21:28:35.635Z pw:api   "networkidle" event fired
2021-11-03T21:28:40.076Z pw:api <= locator.click failed
================= Original suppressed error =================
locator.click: Timeout 5000ms exceeded.
=========================== logs ===========================
waiting for selector "xpath=//button[contains(text(),'Next')]"
  selector resolved to visible <button disabled="true" _nghost-omj-c17="" class="button…> Next </button>
attempting click action
  waiting for element to be visible, enabled and stable
    element is not enabled - waiting...
============================================================
    at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:25847:50
    at step (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:25681:23)
    at Object.next (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:25662:53)
    at fulfilled (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/index.js:25653:58) {
  name: 'TimeoutError'
}
=============================================================
2021-11-03T21:28:40.081Z pw:api => page.screenshot started
2021-11-03T21:28:40.192Z pw:api <= page.screenshot succeeded
{"level":30,"time":"2021-11-03T21:28:40.209Z","pid":32333,"hostname":"Host","msg":"currentBrowser: [object Object]"}
{"level":30,"time":"2021-11-03T21:28:40.209Z","pid":32333,"hostname":"Host","msg":"Trace file: "}
2021-11-03T21:28:40.209Z pw:api => browser.newContext started
2021-11-03T21:28:40.214Z pw:api <= browser.newContext succeeded
2021-11-03T21:28:40.215Z pw:api => browserContext.addInitScript started
2021-11-03T21:28:40.215Z pw:api <= browserContext.addInitScript succeeded
{"level":30,"time":"2021-11-03T21:28:40.215Z","pid":32333,"hostname":"Host","msg":"Changed active context"}
2021-11-03T21:28:40.219Z pw:api => page.title started
2021-11-03T21:28:40.220Z pw:api <= page.title succeeded
{"level":30,"time":"2021-11-03T21:28:40.223Z","pid":32333,"hostname":"Host","msg":"Changed active context"}
{"level":30,"time":"2021-11-03T21:28:40.223Z","pid":32333,"hostname":"Host","msg":"Changing current active page"}
{"level":30,"time":"2021-11-03T21:28:40.223Z","pid":32333,"hostname":"Host","msg":"Changed active page"}
2021-11-03T21:28:40.224Z pw:api => page.bringToFront started
2021-11-03T21:28:40.226Z pw:api <= page.bringToFront succeeded
2021-11-03T21:28:40.229Z pw:api => page.title started
2021-11-03T21:28:40.230Z pw:api <= page.title succeeded
{"level":30,"time":"2021-11-03T21:28:40.236Z","pid":32333,"hostname":"Host","msg":"Changed active context"}
{"level":30,"time":"2021-11-03T21:28:40.237Z","pid":32333,"hostname":"Host","msg":"Changing current active page"}
{"level":30,"time":"2021-11-03T21:28:40.237Z","pid":32333,"hostname":"Host","msg":"Changed active page"}
2021-11-03T21:28:40.237Z pw:api => page.bringToFront started
2021-11-03T21:28:40.238Z pw:api <= page.bringToFront succeeded
2021-11-03T21:28:40.240Z pw:api => browserContext.close started
2021-11-03T21:28:40.288Z pw:api <= browserContext.close succeeded
{"level":30,"time":"2021-11-03T21:28:40.290Z","pid":32333,"hostname":"Host","msg":"Changed active context"}
{"level":30,"time":"2021-11-03T21:28:40.298Z","pid":32333,"hostname":"Host","msg":"Changed active context"}
2021-11-03T21:28:40.299Z pw:api => browserContext.close started
2021-11-03T21:28:40.301Z pw:api <= browserContext.close succeeded
2021-11-03T21:28:40.306Z pw:api => browser.close started
2021-11-03T21:28:40.474Z pw:api <= browser.close succeeded
```
Also this is an image of the trace in the logs:
v10.0.2
<img width="637" alt="Screenshot 2021-11-03 at 21 38 19" src="https://user-images.githubusercontent.com/72198546/140196790-a1b38ec3-7b1f-4669-9a49-4cab3c88090a.png">

Same keyword in v9.0.2
<img width="1246" alt="Screenshot 2021-11-03 at 21 40 44" src="https://user-images.githubusercontent.com/72198546/140196923-ff0c1966-a6f9-4c5d-9cf0-9101aad967dd.png">

**Comment by aaltat** [comment]
@allcontributors please add @GavinRodgers-EN0055 for bugs

**Comment by aaltat** [comment]
Ah, I think I know what is wrong, before 10.x release, [Get Element(s)](https://github.com/MarketSquare/robotframework-browser/blob/v9.0.2/node/playwright-wrapper/evaluation.ts#L53) keywords did wait that at least one element is in attached state. But in 10.x release we do not anymore wait that and this is a regression bug. 

Need to think how to reproduce the problem and fix it.
