### ISSUE TITLE
Chromium: Check Checkbox KW fails sometimes with Element is not attached to the DOM

### ISSUE THREAD

**Issue by zastress** [MarketSquare/robotframework-browser#1492]
**Describe the bug**

Checking the checkbox sometimes fails with new Browser 10.0.3. This bug was observer by running the same test on chromium and firefox. Problem seems to be present only on chromium browser.
This bug was not observed prior to 10.0.3 version.

**To Reproduce**
1. Go to a page with some input fields on it and a checkbox
2. Fill text inside input fields (`Fill Text`) and then enable the checkbox (`Check Checkbox`)
3. Do the same action as above (now the checkbox is already enabled so the `Check Checkbox` keyword should not have any effect)
4. Test fails with error: `Element is not attached to the DOM`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chromium
 - Version 10.0.3

**Logs**
```
{"level":30,"time":"2021-11-09T09:43:18.223Z","pid":21616,"hostname":"DESKTOP-T1MM03J","msg":"Strict mode is enabled, find Locator with //div[contains(@class,'success-box')][contains(text(),'Configuration applied.')] in page."}
2021-11-09T09:43:18.223Z pw:api => locator.waitFor started
2021-11-09T09:43:18.224Z pw:api waiting for selector "//div[contains(@class,'success-box')][contains(text(),'Configuration applied.')]" to be visible
2021-11-09T09:43:18.229Z pw:api   selector resolved to visible <div _ngcontent-tif-c8="" class="success-box ng-star-…> Configuration applied. </div>
2021-11-09T09:43:18.231Z pw:api <= locator.waitFor succeeded
{"level":30,"time":"2021-11-09T09:43:18.235Z","pid":21616,"hostname":"DESKTOP-T1MM03J","msg":"Strict mode is enabled, find Locator with //div[@formgroupname=\"secondary\"]//mat-checkbox/label in page."}
2021-11-09T09:43:18.235Z pw:api => locator.check started
2021-11-09T09:43:18.235Z pw:api waiting for selector "//div[@formgroupname="secondary"]//mat-checkbox/label"
2021-11-09T09:43:18.243Z pw:api   selector resolved to visible <label for="mat-checkbox-3-input" class="mat-checkbox-l…>…</label>
2021-11-09T09:43:18.262Z pw:api <= locator.check failed
================= Original suppressed error =================
locator.check: Element is not attached to the DOM
=========================== logs ===========================
waiting for selector "//div[@formgroupname="secondary"]//mat-checkbox/label"
  selector resolved to visible <label for="mat-checkbox-3-input" class="mat-checkbox-l…>…</label>
============================================================
    at c:\python3.8\lib\site-packages\Browser\wrapper\index.js:25922:50
    at step (c:\python3.8\lib\site-packages\Browser\wrapper\index.js:25695:23)
    at Object.next (c:\python3.8\lib\site-packages\Browser\wrapper\index.js:25676:53)
    at fulfilled (c:\python3.8\lib\site-packages\Browser\wrapper\index.js:25667:58) {
  name: 'Error'
}
=============================================================
```

**Comment by aaltat** [comment]
The 9.0 implementation did call [page.check](https://playwright.dev/docs/api/class-page#page-check) Playwright method under the hood. The 10.0 uses [locator.check](https://playwright.dev/docs/api/class-locator#locator-check). According Playwright documentation, `page.check` will first do: `Find an element matching selector. If there is none, wait until a matching element is attached to the DOM.`. But the `locator.check` documentation says: `If the element is detached from the DOM at any moment during the action, this method throws.` Most likely the fix is to make keyword wait that element is attached to the page. If it is that fault, fix is easy to do, but need to think how to test it so that I actually fix the right problem.

**Comment by zastress** [comment]
I could retest the fix once in place using my same scenario.

**Comment by aaltat** [comment]
That will help in many ways. In any case I will spend some time figuring how to test this one, because tests are safety net. Also it is clear that we did not have test for this feature and we can accidentally break this functionality. Like we already did with 10.0 release and test can help us stop missing features already in development phase.

**Comment by zastress** [comment]
Problem is that I tried to come up with a case to replicate the issue but I was unable to do it on a demo public website. If it helps, in my test case there is a toast overlapping the checkbox for just a fraction of a second. I am guessing that is what's causing the issue, playwright does not wait for the element to be clickable.

**Comment by aaltat** [comment]
I can reproduce the problem with 10.0 and 9.0 release. It is some sort of timing issue and it indeed raises an exception sometimes. I see this with 10.0 release
```
{"level":30,"time":"2021-11-13T23:07:28.254Z","pid":53919,"hostname":"Tatus-Air","msg":"Strict mode is enabled, find Locator with #victim in page."}
2021-11-13T23:07:28.255Z pw:api => locator.check started
2021-11-13T23:07:28.255Z pw:api waiting for selector "#victim"
2021-11-13T23:07:28.705Z pw:api   "networkidle" event fired
2021-11-13T23:07:28.970Z pw:api   selector resolved to visible <input checked id="victim" type="checkbox"/>
2021-11-13T23:07:28.973Z pw:api <= locator.check failed
================= Original suppressed error =================
locator.check: Element is not attached to the DOM
=========================== logs ===========================
waiting for selector "#victim"
  selector resolved to visible <input checked id="victim" type="checkbox"/>
============================================================
    at /Users/tatuaalto/workspace/robotframework-playwright/Browser/wrapper/index.js:24860:50
    at step (/Users/tatuaalto/workspace/robotframework-playwright/Browser/wrapper/index.js:24630:23)
    at Object.next (/Users/tatuaalto/workspace/robotframework-playwright/Browser/wrapper/index.js:24611:53)
    at fulfilled (/Users/tatuaalto/workspace/robotframework-playwright/Browser/wrapper/index.js:24602:58) {
  name: 'Error'
}
=============================================================
```
With 9.0 release I see
```
{"level":30,"time":"2021-11-13T23:18:31.543Z","pid":55977,"hostname":"Tatus-Air","msg":"Page|Frame|Element resolved elementSelector: #victim"}
2021-11-13T23:18:31.543Z pw:api => page.$ started
2021-11-13T23:18:31.544Z pw:api     finding element using the selector "#victim"
2021-11-13T23:18:31.544Z pw:api <= page.$ succeeded
2021-11-13T23:18:31.544Z pw:api => page.check started
2021-11-13T23:18:31.544Z pw:api waiting for selector "#victim"
2021-11-13T23:18:31.995Z pw:api   "networkidle" event fired
2021-11-13T23:18:32.259Z pw:api   selector resolved to visible <input checked id="victim" type="checkbox"/>
2021-11-13T23:18:32.266Z pw:api <= page.check failed
================= Original suppressed error =================
page.check: Element is not attached to the DOM
=========================== logs ===========================
waiting for selector "#victim"
  selector resolved to visible <input checked id="victim" type="checkbox"/>
============================================================
    at /Users/tatuaalto/workspace/robotframework-playwright/Browser/wrapper/index.js:26429:45
    at step (/Users/tatuaalto/workspace/robotframework-playwright/Browser/wrapper/index.js:26312:23)
    at Object.next (/Users/tatuaalto/workspace/robotframework-playwright/Browser/wrapper/index.js:26293:53)
    at fulfilled (/Users/tatuaalto/workspace/robotframework-playwright/Browser/wrapper/index.js:26284:58) {
  name: 'Error'
}
=============================================================
```

Event the problem has existed with older version, it is still a problem/bug. I need to think how to fix it.

**Comment by aaltat** [comment]
Also this is not regression with Playwright, I tried with PW 1.15.2 and 1.16.2 and results are same. Randomly both versions fails at same reason.

**Comment by zastress** [comment]
Great job investigating the issue. Waiting for the fix :). Thanks for the effort!

**Comment by aaltat** [comment]
I did discuss with the rest of the team about how to fix this. Basically I did decide to wait for the attached state in the node side. At the same time, we know that this fix might not help in all situations. But because it is difficult problem to solve, something more custom might be needed. If the problem persist after a new release, please lets us know and lets see what could be done.
