### ISSUE TITLE
Unable to init the browser library

### ISSUE THREAD

**Issue by akashyap1** [MarketSquare/robotframework-browser#1675]
**Describe the bug**
Unable to init the browser library, rfbrowser is not recognized and tried below command
python -m Browser.entry init
Traceback (most recent call last):
  File "C:\Dev\Python\Python38\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Dev\Python\Python38\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Dev\Python\Python38\Lib\site-packages\Browser\__init__.py", line 15, in <module>
    from .browser import Browser
  File "C:\Dev\Python\Python38\Lib\site-packages\Browser\browser.py", line 43, in <module>
    from .playwright import Playwright
  File "C:\Dev\Python\Python38\Lib\site-packages\Browser\playwright.py", line 23, in <module>
    from backports.cached_property import cached_property
ModuleNotFoundError: No module named 'backports.cached_property'

**To Reproduce**
1. Respected versions are:
robotframework                  3.1.2
robotframework-browser          3.0.0
node    v14.11.0
Python    3.8

We also tried with robotframework-browser version 11.1.1 but getting the same error

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by aaltat** [comment]
Robot Framework 3.x is not supported by this library. Use latest Robot Framework release.
