### ISSUE TITLE
Windows 10 - rfbrowser init command throwing an error "RuntimeError: Problem installing node dependencies.Node process returned with exit status 1"

### ISSUE THREAD

**Issue by akhilPanickerJPL** [MarketSquare/robotframework-browser#1893]
Running `rfbrowser init` throws an error `RuntimeError: Problem installing node dependencies.Node process returned with exit status 1`
Already installed - Python (3.10.2), pip (22.0.4), Robot Framework (5), nodejs (16.14.2)

**To Reproduce**
1. Install Python, pip, robot framework and node js (versions listed above)
2. Run `pip install robotframework-browser` - Works fine
3. Run `rfbrowser init`
4. Getting below error
```
Installing node dependencies...
Installing rfbrowser node dependencies at C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Browser\wrapper
npm ERR! code SELF_SIGNED_CERT_IN_CHAIN

npm ERR! errno SELF_SIGNED_CERT_IN_CHAIN

npm ERR! request to https://registry.npmjs.org/yazl/-/yazl-2.5.1.tgz failed, reason: self signed certificate in certificate chain

npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2022-03-23T20_10_42_753Z-debug-0.log

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\rfbrowser.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Browser\entry.py", line 237, in run
    rfbrowser_init(args.skip_browsers)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Browser\entry.py", line 53, in rfbrowser_init
    raise error
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Browser\entry.py", line 45, in rfbrowser_init
    _rfbrowser_init(skip_browser_install, install_file)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Browser\entry.py", line 153, in _rfbrowser_init
    raise RuntimeError(
RuntimeError: Problem installing node dependencies.Node process returned with exit status 1
```

OS details:
Windows 10

PFA logs.

[_logs.zip](https://github.com/MarketSquare/robotframework-browser/files/8336381/_logs.zip)

**Comment by akhilPanickerJPL** [comment]
Got the fix. For now, disabled strict ssl mode in npm.

[Workaround mentioned here](https://stackoverflow.com/questions/29141153/nodejs-npm-err-code-self-signed-cert-in-chain).

Closing the ticket.
