### ISSUE TITLE
rfbrowser init stuck forever

### ISSUE THREAD

**Issue by TimmyLin-Avancevl** [MarketSquare/robotframework-browser#1969]
**Describe the bug**
rfbrowser init stuck forever

**To Reproduce**
I am using virtualenv and nodeenv to setup rfbrowser
but rfbrowser init stuck forever until I manually terminate it
```
(.venv) C:\Users\TimmyLin\Documents\Work_Project\autotest>rfbrowser init
Installing node dependencies...
Installing rfbrowser node dependencies at C:\Users\TimmyLin\Documents\Work_Project\autotest\.venv\lib\site-packages\Browser\wrapper
npm WARN old lockfile

npm WARN old lockfile The package-lock.json file was created with an old version of npm,

npm WARN old lockfile so supplemental metadata must be fetched from the registry.

npm WARN old lockfile

npm WARN old lockfile This is a one-time fix-up, please be patient...

npm WARN old lockfile

Traceback (most recent call last):
  File "C:\Users\TimmyLin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\TimmyLin\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\TimmyLin\Documents\Work_Project\autotest\.venv\Scripts\rfbrowser.exe\__main__.py", line 7, in <module>
  File "C:\Users\TimmyLin\Documents\Work_Project\autotest\.venv\lib\site-packages\Browser\entry.py", line 237, in run
    rfbrowser_init(args.skip_browsers)
  File "C:\Users\TimmyLin\Documents\Work_Project\autotest\.venv\lib\site-packages\Browser\entry.py", line 45, in rfbrowser_init
    _rfbrowser_init(skip_browser_install, install_file)
  File "C:\Users\TimmyLin\Documents\Work_Project\autotest\.venv\lib\site-packages\Browser\entry.py", line 148, in _rfbrowser_init
    output = process.stdout.readline().decode("UTF-8")
KeyboardInterrupt
^C
```

Check %\AppData\Local\npm-cache\_logs\2022-04-17T15_26_46_453Z-debug-0.log
```
....
1416 timing build:link:node_modules/playwright-core Completed in 1ms
1417 timing build:link:node_modules/playwright-core/node_modules/mime Completed in 34ms
1418 timing build:link:node_modules/pino Completed in 35ms
1419 timing build:link:node_modules/extract-zip Completed in 35ms
1420 timing build:link:node_modules/@grpc/proto-loader Completed in 36ms
1421 timing build:link:node_modules/playwright Completed in 35ms
1422 timing build:link:node_modules/pixelmatch Completed in 37ms
1423 timing build:link:node_modules/rimraf Completed in 36ms
1424 timing build:link:node_modules/uuid Completed in 36ms
1425 timing build:link:node_modules/protobufjs Completed in 36ms
1426 timing build:link Completed in 38ms
1427 info run playwright@1.20.1 install node_modules/playwright node install.js    <--- The process stuck here forever until I termiante it and show below error
1428 info run playwright@1.20.1 install { code: 1, signal: null }
1429 timing reify:rollback:createSparse Completed in 530ms
1430 timing reify:rollback:retireShallow Completed in 0ms
1431 timing command:ci Completed in 285770ms
1432 verbose stack Error: command failed
1432 verbose stack     at ChildProcess.<anonymous> (C:\Users\TimmyLin\Documents\Work_Project\autotest\.venv\Scripts\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
1432 verbose stack     at ChildProcess.emit (node:events:526:28)
1432 verbose stack     at maybeClose (node:internal/child_process:1092:16)
1432 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
1433 verbose pkgid playwright@1.20.1
1434 verbose cwd C:\Users\TimmyLin\Documents\Work_Project\autotest\.venv\lib\site-packages\Browser\wrapper
1435 verbose Windows_NT 10.0.19044
1436 verbose argv "C:\\Users\\TimmyLin\\Documents\\Work_Project\\autotest\\.venv\\Scripts\\node.exe" "C:\\Users\\TimmyLin\\Documents\\Work_Project\\autotest\\.venv\\Scripts\\node_modules\\npm\\bin\\npm-cli.js" "ci" "--production"
1437 verbose node v16.14.2
1438 verbose npm  v8.5.0
1439 error code 1
1440 error path C:\Users\TimmyLin\Documents\Work_Project\autotest\.venv\lib\site-packages\Browser\wrapper\node_modules\playwright
1441 error command failed
1442 error command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
1443 verbose exit 1
1444 timing npm Completed in 286266ms
1445 verbose unfinished npm timer reify 1650209216904
1446 verbose unfinished npm timer reify:build 1650209220144
1447 verbose unfinished npm timer build 1650209220145
1448 verbose unfinished npm timer build:deps 1650209220145
1449 verbose unfinished npm timer build:run:install 1650209220201
1450 verbose unfinished npm timer build:run:install:node_modules/playwright 1650209220201
1451 verbose code 1
1452 error A complete log of this run can be found in:
1452 error     C:\Users\TimmyLin\AppData\Local\npm-cache\_logs\2022-04-17T15_26_46_453Z-debug-0.log

```

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 19044.1645
 - robotframework-browser version: 12.3.0
 - nodeenv nodejs version: v16.14.2 lts
 - virtualenv python version: 3.10.1

**Comment by TimmyLin-Avancevl** [comment]
Trace the code and it stuck at `npm ci --production` 
manually run it with --verbose and found that it hangs forever in this step
![image](https://user-images.githubusercontent.com/97291729/163723537-50ac5762-92e5-4a44-91bf-4bc3196b5dde.png)

However .. I doubt this may be a network issue due to I found this bug
https://github.com/microsoft/playwright/issues/13578

and I did try the same scripts on the remote server
(which is not the same location from my local client, and the playwright install did succeed on the remote server ..)

**Comment by aaltat** [comment]
Playwright 1.21.1 is merged to main code line and it contains fix for the https://github.com/microsoft/playwright/issues/13530 Next release should fix this problem.

**Comment by TimmyLin-Avancevl** [comment]
I can download playwright properly now. Thanks.
