### ISSUE TITLE
Wait For Navigation fails: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by ealap** [MarketSquare/robotframework-browser#2081]
**Describe the bug**
Promise to wait for navigation fails due to library error:
```
'str' object has no attribute 'name'
```

**To Reproduce**
```
Click "${locator}" And Wait For Navigation To "${target}" Page Until "${event}"
    ${target_url} =    Resolve Full Url    ${target}
    ${page_navigation} =    Promise To    Wait For Navigation    url=${target_url}    wait_until=${event}
    Click    ${selector}
    Wait For    ${page_navigation}
```
`wait_until` has value `load` during test.

**Expected behavior**
Promise to wait for navigation should be successful.

**Traceback**
```
Traceback (most recent call last):
  File "/home/robot/testenv/lib/python3.10/site-packages/Browser/playwright.py", line 149, in grpc_channel
    yield playwright_pb2_grpc.PlaywrightStub(self._channel)
  File "/home/robot/testenv/lib/python3.10/site-packages/Browser/keywords/network.py", line 245, in wait_for_navigation
    waitUntil=wait_until.name,
AttributeError: 'str' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/robot/testenv/lib/python3.10/site-packages/Browser/browser.py", line 957, in run_keyword
    raise e
  File "/home/robot/testenv/lib/python3.10/site-packages/Browser/browser.py", line 947, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "/home/robot/testenv/lib/python3.10/site-packages/robotlibcore.py", line 94, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "/home/robot/testenv/lib/python3.10/site-packages/Browser/keywords/promises.py", line 166, in wait_for
    return promises[0].result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/robot/testenv/lib/python3.10/site-packages/Browser/keywords/network.py", line 238, in wait_for_navigation
    with self.playwright.grpc_channel() as stub:
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/robot/testenv/lib/python3.10/site-packages/Browser/playwright.py", line 156, in grpc_channel
    raise AssertionError(str(error))
AssertionError: 'str' object has no attribute 'name'
```

**Additional context**
- Tested working until `robotframework-browser v12.1.0`
- Tested breaking since `robotframework-browser v12.2.0`

**Comment by luchoagomezt** [comment]
@aaltat Please have a look at [PR 2100](https://github.com/MarketSquare/robotframework-browser/pull/2100)

**Comment by luchoagomezt** [comment]
@ealap PR 2100 fiexes the issue

**Comment by aaltat** [comment]
Done in https://github.com/MarketSquare/robotframework-browser/commit/c0929586f984e136bd4acdd57c34318301a65cc8
