### ISSUE TITLE
Check Checkbox throws Exception, even with force=True

### ISSUE THREAD

**Issue by robinmackaij-kadaster** [MarketSquare/robotframework-browser#2173]
**Describe the bug**
`Check Checkbox` changed checkbox state (confirmed by `Get Element States` before `Check Checkbox` and after the exception occured) but still an exception is thrown:
> Suspended due to logged failure: Error: locator.check: Clicking the checkbox did not change its state

This exception occurs even if `force=True` is used, so there appear to be two bugs:
1. Element state changed not detected (possibly due to short timeout - the error occurs after 1 ms after the click)
2. `force` flag is ignored

**Expected behavior**
1. No exception if the state change of the element is not instantly, a (small) timeout should apply (the regular assertion timeout?)
2. No exception if the `force` flag is set to `True`

**Screenshot**
![image](https://user-images.githubusercontent.com/97301504/178214102-1cb9f94e-f251-4399-bb54-3a2016449cf4.png)

**Desktop**
 - OS: Windows 10
 - Browser: chrome
 - Version: Browser 13.1.0

**Playwright trace log:**
```
{"level":30,"time":"2022-07-08T13:26:23.296Z","pid":10424,"hostname":"LT0249203","msg":"element=cb6aa134-9c4c-404b-ae01-4341eff0e99b selector parsed without children"}
{"level":30,"time":"2022-07-08T13:26:23.296Z","pid":10424,"hostname":"LT0249203","msg":"Only locator handle defined, return cached Locator."}
2022-07-08T13:26:23.297Z pw:api => locator.waitFor started
2022-07-08T13:26:23.297Z pw:api waiting for selector "id=dso-portal-frame >> nth=0 >> control=enter-frame >> //input[@type="checkbox"] >> nth=1"
2022-07-08T13:26:23.297Z pw:api   waiting for frame "id=dso-portal-frame >> nth=0"
2022-07-08T13:26:23.301Z pw:api   selector resolved to visible <iframe scrolling="no" allowfullscreen="" class="ng-tns-…></iframe>
2022-07-08T13:26:23.310Z pw:api   selector resolved to visible <input checked type="checkbox" aria-describedby="" aria…/>
2022-07-08T13:26:23.312Z pw:api <= locator.waitFor succeeded
2022-07-08T13:26:23.312Z pw:api => locator.check started
2022-07-08T13:26:23.313Z pw:api   waiting for frame "id=dso-portal-frame >> nth=0"
2022-07-08T13:26:23.316Z pw:api   selector resolved to visible <iframe scrolling="no" allowfullscreen="" class="ng-tns-…></iframe>
2022-07-08T13:26:23.331Z pw:api waiting for selector "id=dso-portal-frame >> nth=0 >> control=enter-frame >> //input[@type="checkbox"] >> nth=1"
2022-07-08T13:26:23.333Z pw:api   selector resolved to visible <input checked type="checkbox" aria-describedby="" aria…/>
2022-07-08T13:26:23.338Z pw:api attempting click action
2022-07-08T13:26:23.338Z pw:api   waiting for element to be visible, enabled and stable
2022-07-08T13:26:23.341Z pw:api     forcing action
2022-07-08T13:26:23.344Z pw:api   element is visible, enabled and stable
2022-07-08T13:26:23.344Z pw:api   scrolling into view if needed
2022-07-08T13:26:23.345Z pw:api   done scrolling
2022-07-08T13:26:23.346Z pw:api   performing click action
2022-07-08T13:26:23.360Z pw:api   click action done
2022-07-08T13:26:23.360Z pw:api   waiting for scheduled navigations to finish
2022-07-08T13:26:23.361Z pw:api   navigations have finished
2022-07-08T13:26:23.368Z pw:api <= locator.check failed
{"level":30,"time":"2022-07-08T13:26:23.368Z","pid":10424,"hostname":"LT0249203","msg":"Error of node method  checkCheckbox"}
================= Original suppressed error =================
locator.check: Clicking the checkbox did not change its state
=========================== logs ===========================
  waiting for frame "id=dso-portal-frame >> nth=0"
  selector resolved to visible <iframe scrolling="no" allowfullscreen="" class="ng-tns-…></iframe>
waiting for selector "id=dso-portal-frame >> nth=0 >> control=enter-frame >> //input[@type="checkbox"] >> nth=1"
  selector resolved to visible <input checked type="checkbox" aria-describedby="" aria…/>
attempting click action
  waiting for element to be visible, enabled and stable
    forcing action
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  click action done
  waiting for scheduled navigations to finish
  navigations have finished
============================================================
    at checkCheckbox (c:\GitHub\InitiatiefBoT\.venv\lib\site-packages\Browser\wrapper\index.js:7152:17)
    at async PlaywrightServer.checkCheckbox (c:\GitHub\InitiatiefBoT\.venv\lib\site-packages\Browser\wrapper\index.js:7996:28) {
  name: 'Error'
}
=============================================================
{"level":30,"time":"2022-07-08T13:26:23.380Z","pid":10424,"hostname":"LT0249203","msg":"Start of node method takeScreenshot"}
2022-07-08T13:26:23.381Z pw:api => page.screenshot started
2022-07-08T13:26:23.382Z pw:api taking page screenshot
2022-07-08T13:26:23.543Z pw:api <= page.screenshot succeeded
{"level":30,"time":"2022-07-08T13:26:23.547Z","pid":10424,"hostname":"LT0249203","msg":"End of node method takeScreenshot"}
```

**Comment by aaltat** [comment]
@allcontributors please add @robinmackaij-kadaster for bugs

**Comment by aaltat** [comment]
Is this still valid bug with latest Browser and Playwright release?

**Comment by robinmackaij-kadaster** [comment]
Just double-checked with Browser 14.1.0 and I still have a Checkbox where this issue occurs (on other Checkboxes in the application I have no issues). I do believe it is something in the implementation of that Checkbox / the state behind it though. If I breakpoint at the Check Checkbox line it'll run fine. Without the breakpoint it'll fail with the above error every time (even though the element is visually checked by the failing keyword call).

The same behavior also occurs with Uncheck Checkbox on the same Checkbox after I check it using breakpoint or forced Click so I believe this is (mostly) an implementation issue in this particular element.

It's still strange that the force flag does not change the behavior of Check Checkbox on this element at all though. That's perhaps a part that can be looked into; I'm afraid the particular Checkbox is not publically available so I have no idea how it could be reproduced elsewhere. I'll close this for this reason.
