### ISSUE TITLE
Nodejs 18 is not supported

### ISSUE THREAD

**Issue by rlall07** [MarketSquare/robotframework-browser#2605]
**Describe the bug**
Unable to run `rfbrowser init` successfully with NodeJS 18. 

**To Reproduce**
1. Installed python 3.10.9
2. Installed latest Nodejs which was v18.13.0
3. Installed robotframework_browser
4. ran rfbrowser init

npm --version
9.4.0
python --version
Python 3.10.9
node --version
v18.13.0
robotframework-browser==15.1.0

Error seen: 
`rfbrowser init
2023-01-26 15:01:33,151 [INFO    ] ==============================================================================================================
2023-01-26 15:01:33,153 [INFO    ] Installing node dependencies...
2023-01-26 15:01:33,153 [INFO    ] Installing rfbrowser node dependencies at C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\wrapper
2023-01-26 15:01:35,669 [INFO    ] npm WARN config production Use `--omit=dev` instead.

2023-01-26 15:02:12,068 [INFO    ] npm ERR! code 1

2023-01-26 15:02:12,068 [INFO    ] npm ERR! path C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\wrapper\node_modules\playwright

2023-01-26 15:02:12,068 [INFO    ] npm ERR! command failed

2023-01-26 15:02:12,068 [INFO    ] npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js

2023-01-26 15:02:12,068 [INFO    ] npm ERR! Downloading Chromium 109.0.5414.46 (playwright build v1041) from https://playwright.azureedge.net/builds/chromium/1041/chromium-win64.zip

2023-01-26 15:02:12,068 [INFO    ] npm ERR! |                                                                                |   0% of 110.2 Mb

--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 45-52: character maps to <undefined>
Call stack:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\entry.py", line 297, in <module>
    main()
  File "C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\entry.py", line 293, in main
    runner(command, skip_browsers, trace_file)
  File "C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\entry.py", line 235, in runner
    rfbrowser_init(skip_browsers)
  File "C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\entry.py", line 62, in rfbrowser_init
    _rfbrowser_init(skip_browser_install)
  File "C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\entry.py", line 167, in _rfbrowser_init
    logging.info(output)
Message: 'npm ERR! |■■■■■■■■                                                                        |  10% of 110.2 Mb\n'
Arguments: ()
.....
....

2023-01-26 15:02:14,058 [INFO    ] ==============================================================================================================
2023-01-26 15:02:15,222 [INFO    ] npm version is:n
2023-01-26 15:02:15,222 [INFO    ] 8.19.3

2023-01-26 15:02:15,222 [INFO    ] ==============================================================================================================
2023-01-26 15:02:15,222 [INFO    ] Installation directory `C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\wrapper` does not contain the required files
Printing contents:

2023-01-26 15:02:15,222 [INFO    ] wrapper/

2023-01-26 15:02:15,222 [INFO    ]     index.js

2023-01-26 15:02:15,222 [INFO    ]     package-lock.json

2023-01-26 15:02:15,222 [INFO    ]     package.json

2023-01-26 15:02:15,222 [INFO    ]     static/

2023-01-26 15:02:15,222 [INFO    ]         selector-finder.js

2023-01-26 15:02:15,222 [INFO    ] ==============================================================================================================
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\entry.py", line 297, in <module>
    main()
  File "C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\entry.py", line 293, in main
    runner(command, skip_browsers, trace_file)
  File "C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\entry.py", line 235, in runner
    rfbrowser_init(skip_browsers)
  File "C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\entry.py", line 70, in rfbrowser_init
    raise error
  File "C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\entry.py", line 62, in rfbrowser_init
    _rfbrowser_init(skip_browser_install)
  File "C:\Users\rlall\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\Browser\entry.py", line 172, in _rfbrowser_init
    raise RuntimeError(
RuntimeError: Problem installing node dependencies.Node process returned with exit status 1`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aaltat** [comment]
@allcontributors please add @rlall07 for ideas.

**Comment by Snooz82** [comment]
I double checked and this is not a Problem of node 18. node 18 works with Browser

**Comment by paguilera** [comment]
Does this mean that Node 18 is officially supported?
