### ISSUE TITLE
KWD Take Screenshot Failing with Firefox Browser

### ISSUE THREAD

**Issue by ZephyrusMB** [MarketSquare/robotframework-browser#2693]
KWD Take Screenshot fails  with error "SyntaxError: page.screenshot: Unexpected token u in
 JSON at position 0" when used with firefox browser with following details

17:44:43.818 DEBUG Traceback (most recent call last): File "C:\Users\sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\Browser\playwright.py", line 158, in grpc_channel yield playwright_pb2_grpc.PlaywrightStub(self._channel) File "C:\Users\sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\Browser\keywords\browser_control.py",
 line 187, in take_screenshot response = stub.TakeScreenshot( File "C:\Users\sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py", line 946, in __call__ return _end_unary_response_blocking(state, call, False, None) File "C:\Users\sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\grpc\_channel.py",
 line 849, in _end_unary_response_blocking raise _InactiveRpcError(state) grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with: status = StatusCode.RESOURCE_EXHAUSTED details = "SyntaxError: page.screenshot: Unexpected token u in
 JSON at position 0 =========================== logs =========================== taking page screenshot ============================================================" debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:65162 {grpc_message:"SyntaxError:
 page.screenshot: Unexpected token u in JSON at position 0\n=========================== logs ===========================\ntaking page screenshot\n============================================================", grpc_status:8, created_time:"2023-03-13T16:44:43.69851083+00:00"}"
 > During handling of the above exception, another exception occurred: Traceback (most recent call last): File "C:\Users\sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\Browser\browser.py", line 1121, in run_keyword raise e File "C:\Users\sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\Browser\browser.py",
 line 1110, in run_keyword return DynamicCore.run_keyword(self, name, args, kwargs) File "C:\Users\sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\robotlibcore.py", line 122, in run_keyword return self.keywords[name](*args, **(kwargs or {}))
 File "C:\Users\sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\Browser\keywords\browser_control.py", line 176, in take_screenshot with self.playwright.grpc_channel() as stub: File "C:\Users\sergio\AppData\Local\Programs\Python\Python310\lib\contextlib.py",
 line 153, in __exit__ self.gen.throw(typ, value, traceback) File "C:\Users\sergio\AppData\Local\Programs\Python\Python310\lib\site-packages\Browser\playwright.py", line 162, in grpc_channel raise AssertionError(error.details()) AssertionError: SyntaxError:
 page.screenshot: Unexpected token u in JSON at position 0 =========================== logs =========================== taking page screenshot ============================================================

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/81178328/224772735-8763ce15-f65a-42df-81d8-632f90c57950.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 versione 21H2
 - Browser: firefox
 - Version browserLibrary version 16.0.0

**Comment by Snooz82** [comment]
is fixed by Playwright 1.31.2 and therefore fixed with Browser v16.0.1

**Comment by ZephyrusMB** [comment]
thank  you
