### ISSUE TITLE
ConnectionError: Playwright process has been terminated with code

### ISSUE THREAD

**Issue by JaPyR** [MarketSquare/robotframework-browser#2858]
**Describe the bug**
Recently I've started getting a lot of errors where my browser hangs for a while and after any interaction with browser ends with error  "ConnectionError: Playwright process has been terminated with code".  Happens in Gitlab and on local Windows machine. Appears in  random parts of different test cases so I do not have steps to reproduce, but maybe you could spot some bug based on robot and playwright logs.

In recent run on local machine flow was the following:
1. It's started with error in `Wait For Elements State` keyword.

playwright:
```
2023-06-15T08:51:27.538Z pw:api => locator.waitFor started
2023-06-15T08:51:27.538Z pw:api waiting for locator('*****************************************************************') to be visible
2023-06-15T08:51:47.537Z pw:api <= locator.waitFor failed
{"level":30,"time":"2023-06-15T08:51:47.537Z","pid":12912,"hostname":"************","msg":"Error of node method  waitForElementState"}
================= Original suppressed error =================
locator.waitFor: Timeout 20000ms exceeded.
=========================== logs ===========================
waiting for locator('*****************************************************************') to be visible
============================================================
    at waitForElementState (C:\Users\********\Docs\code\*********\.venv\lib\site-packages\Browser\wrapper\index.js:8477:19)
    at async PlaywrightServer.waitForElementsState (C:\Users\********\Docs\code\*********\.venv\lib\site-packages\Browser\wrapper\index.js:9987:28) {
  name: 'TimeoutError'
}
=============================================================
```

robot:
```
Arguments: [ '*****************************************************************' ] 	
TimeoutError: locator.waitFor: Timeout 20000ms exceeded.
=========================== logs ===========================
waiting for locator('*****************************************************************') to be visible
============================================================
Tip: Use "Set Browser Timeout" for increasing the timeout or double check your locator as the targeted element(s) couldn't be found. 	
10:51:47.554 	DEBUG 	Traceback (most recent call last):
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\playwright.py", line 160, in grpc_channel
    yield playwright_pb2_grpc.PlaywrightStub(self._channel)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\keywords\waiter.py", line 140, in _wait_for_elements_state
    response = stub.WaitForElementsState(
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\grpc\_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\grpc\_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "TimeoutError: locator.waitFor: Timeout 20000ms exceeded.
=========================== logs ===========================
waiting for locator('*****************************************************************') to be visible
============================================================"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-06-15T08:51:47.556360349+00:00", grpc_status:4, grpc_message:"TimeoutError: locator.waitFor: Timeout 20000ms exceeded.\n=========================== logs ===========================\nwaiting for locator(\'*****************************************************************\') to be visible\n============================================================"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\browser.py", line 1122, in run_keyword
    raise e
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\browser.py", line 1111, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\robotlibcore.py", line 122, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\keywords\waiter.py", line 102, in wait_for_elements_state
    return self._wait_for_elements_state(
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\keywords\waiter.py", line 145, in _wait_for_elements_state
    logger.info(response.log)
  File "C:\Users\********\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\playwright.py", line 164, in grpc_channel
    raise AssertionError(error.details())
AssertionError: TimeoutError: locator.waitFor: Timeout 20000ms exceeded.
=========================== logs ===========================
waiting for locator('*****************************************************************') to be visible
============================================================
Tip: Use "Set Browser Timeout" for increasing the timeout or double check your locator as the targeted element(s) couldn't be found.
```

2. In teardown I try to make screenshot if test failed and than close page and context (I login in suite setup, save storage state and  reuse it to create new context and page in test setup)

playwright:
```
2023-06-15T08:51:47.557Z pw:api => page.screenshot started
2023-06-15T08:51:47.558Z pw:api taking page screenshot
2023-06-15T08:52:07.561Z pw:api <= page.screenshot failed
{"level":30,"time":"2023-06-15T08:52:07.562Z","pid":12912,"hostname":"************","msg":"Error of node method  takeScreenshot"}
================= Original suppressed error =================
page.screenshot: Timeout 20000ms exceeded.
=========================== logs ===========================
taking page screenshot
============================================================
    at takeScreenshot (C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\wrapper\index.js:8324:16)
    at PlaywrightServer.takeScreenshot (C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\wrapper\index.js:9987:34)
    at C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\wrapper\node_modules\@grpc\grpc-js\build\src\server.js:821:17
    at Http2ServerCallStream.safeDeserializeMessage (C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\wrapper\node_modules\@grpc\grpc-js\build\src\server-call.js:395:13)
    at ServerHttp2Stream.onEnd (C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\wrapper\node_modules\@grpc\grpc-js\build\src\server-call.js:382:22) {
  name: 'TimeoutError'
}
=============================================================
```

robot - Screenshot:
```
Arguments: [ 'C:\\Users\\********\\Docs\\code\\e2e-tests\\src\\variables\\..\\..\\artifacts\\screenshots\\browser-screenshot-{index}' | fullPage=True ] 	
Return: None 	
TimeoutError: page.screenshot: Timeout 20000ms exceeded.
=========================== logs ===========================
taking page screenshot
============================================================
Tip: Use "Set Browser Timeout" for increasing the timeout or double check your locator as the targeted element(s) couldn't be found. 	
10:52:07.580 	DEBUG 	Traceback (most recent call last):
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\playwright.py", line 160, in grpc_channel
    yield playwright_pb2_grpc.PlaywrightStub(self._channel)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\keywords\browser_control.py", line 185, in take_screenshot
    response = stub.TakeScreenshot(
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\grpc\_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\grpc\_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "TimeoutError: page.screenshot: Timeout 20000ms exceeded.
=========================== logs ===========================
taking page screenshot
============================================================"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-06-15T08:52:07.57355539+00:00", grpc_status:4, grpc_message:"TimeoutError: page.screenshot: Timeout 20000ms exceeded.\n=========================== logs ===========================\ntaking page screenshot\n============================================================"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\browser.py", line 1122, in run_keyword
    raise e
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\browser.py", line 1111, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\robotlibcore.py", line 122, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\keywords\browser_control.py", line 220, in take_screenshot
    return None
  File "C:\Users\********\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\playwright.py", line 164, in grpc_channel
    raise AssertionError(error.details())
AssertionError: TimeoutError: page.screenshot: Timeout 20000ms exceeded.
=========================== logs ===========================
taking page screenshot
============================================================
Tip: Use "Set Browser Timeout" for increasing the timeout or double check your locator as the targeted element(s) couldn't be found.
```

robot - Close Page:
```
10:52:07.587 	TRACE 	Arguments: [  ] 	
10:52:07.925 	INFO 	[
  {
    "type": "firefox",
    "id": "browser=1e6c408f-907b-45f1-ac2c-08bbf9e32f9a",
    "contexts": [
      {
        "type": "context",
        "id": "context=ca283bd7-8b46-478a-8841-e33e0e3032be",
        "activePage": "page=405f816d-e4fe-4c7e-957e-03c1971695b5",
        "pages": [
          {
            "type": "page",
            "title": null,
            "url": "*****************************************",
            "id": "page=405f816d-e4fe-4c7e-957e-03c1971695b5",
            "timestamp": 1686819082.008
          }
        ]
      }
    ],
    "activeContext": "context=ca283bd7-8b46-478a-8841-e33e0e3032be",
    "activeBrowser": true
  }
] 	
10:52:07.925 	INFO 	Switching browser to CURRENT 	
10:52:07.941 	INFO 	Active context id 	
10:52:07.941 	INFO 	Switching browser to browser=1e6c408f-907b-45f1-ac2c-08bbf9e32f9a 	
10:52:07.941 	INFO 	Successfully changed active browser 	
10:52:07.941 	INFO 	Switching context to CURRENT in CURRENT 	
10:52:07.941 	INFO 	Returned active context id 	
10:52:07.941 	INFO 	Switching context to context=ca283bd7-8b46-478a-8841-e33e0e3032be in CURRENT 	
10:52:08.288 	INFO 	[
  {
    "type": "firefox",
    "id": "browser=1e6c408f-907b-45f1-ac2c-08bbf9e32f9a",
    "contexts": [
      {
        "type": "context",
        "id": "context=ca283bd7-8b46-478a-8841-e33e0e3032be",
        "activePage": "page=405f816d-e4fe-4c7e-957e-03c1971695b5",
        "pages": [
          {
            "type": "page",
            "title": null,
            "url": "*************************************************",
            "id": "page=405f816d-e4fe-4c7e-957e-03c1971695b5",
            "timestamp": 1686819082.008
          }
        ]
      }
    ],
    "activeContext": "context=ca283bd7-8b46-478a-8841-e33e0e3032be",
    "activeBrowser": true
  }
] 	
10:52:08.318 	INFO 	Successfully changed active context 	
10:52:21.365 	TRACE 	Return: None 	
10:52:21.365 	FAIL 	Stream removed 	
10:52:21.385 	DEBUG 	Traceback (most recent call last):
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\playwright.py", line 160, in grpc_channel
    yield playwright_pb2_grpc.PlaywrightStub(self._channel)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\keywords\playwright_state.py", line 283, in close_page
    response = stub.ClosePage(Request().Empty())
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\grpc\_channel.py", line 1030, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\grpc\_channel.py", line 910, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-06-15T08:52:21.37488401+00:00", grpc_status:2, grpc_message:"Stream removed"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\browser.py", line 1122, in run_keyword
    raise e
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\browser.py", line 1111, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\robotlibcore.py", line 122, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\keywords\playwright_state.py", line 286, in close_page
    result.append(
  File "C:\Users\********\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\playwright.py", line 164, in grpc_channel
    raise AssertionError(error.details())
AssertionError: Stream removed
```

robot - Close Context:
```
10:52:21.385 	TRACE 	Arguments: [  ] 	
10:52:23.440 	TRACE 	Return: None 	
10:52:23.440 	FAIL 	ConnectionError: Playwright process has been terminated with code 2147483651 	
10:52:23.440 	DEBUG 	Traceback (most recent call last):
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\browser.py", line 1111, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\robotlibcore.py", line 122, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\keywords\playwright_state.py", line 181, in close_context
    for browser_instance in self._get_browser_ids(browser):
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\keywords\playwright_state.py", line 210, in _get_browser_ids
    catalog = self.get_browser_catalog()
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\assertion_engine.py", line 55, in with_assertion_polling
    return wrapped(*args, **kwargs)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\keywords\playwright_state.py", line 977, in get_browser_catalog
    with self.playwright.grpc_channel() as stub:
  File "C:\Users\********\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\Users\********\Docs\code\e2e-tests\.venv\lib\site-packages\Browser\playwright.py", line 154, in grpc_channel
    raise ConnectionError(
ConnectionError: Playwright process has been terminated with code 2147483651
```

After that any attempt to create new context ends with error `ConnectionError: Playwright process has been terminated with code`.

Additionally at the very end of playwright log there is:
```


#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#
#
#
#FailureMessage Object: 0000009A2F1FE310
 1: 00007FF6362DD51F node_api_throw_syntax_error+175743
 2: 00007FF6361F37BF v8::CTypeInfoBuilder<void>::Build+12703
 3: 00007FF63709D852 V8_Fatal+162
 4: 00007FF636BAAB05 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArray+101
 5: 00007FF636A4EE2E v8::Message::GetIsolate+16478
 6: 00007FF63689AE10 v8::internal::CompilationCache::IsEnabledScriptAndEval+25952
 7: 00007FF636DA8051 v8::internal::SetupIsolateDelegate::SetupHeap+558193
 8: 00007FF5C1D6F5DC 
```

**Comment by JaPyR** [comment]
Versions:
robotframework-browser 16.2.0
robotframework 5.0.1
node v18.16.0

**Comment by aaltat** [comment]
@allcontributors please add @JaPyR for bugs

**Comment by Snooz82** [comment]
Have you tried:

```robotframework
Wait For Condition    Element States    ${locator}    Contains    attached
```

**Comment by Snooz82** [comment]
Maybe it is just time to remove that keyword.

**Comment by JaPyR** [comment]
Looks like I did not mention quite important thing that it was happening in Firefox. After switching to Chromium problem disappeared.

> Maybe it is just time to remove that keyword.

If it's internal implementation is different than `Wait For Condition` maybe it's better to switch it internally, but leave the keyword. Such keyword could be quite popular in tests and removing it will require changes in a lot of places.

**Comment by sd-yazzoom** [comment]
Ok, we found the problem at our end last week, it was completely unrelated after all, just coincidence (what are the odds it failed at the exact same keyword with exactly the same message).

The actual problem in our case was the disk image running out of space (and crashing playwright), since it gets rebuild every time, it failed at exactly the same step (during the Wait For Element keyword), and the error happened to be exactly the same as described in this ticket. A few successful runs on Friday and this weekend seem to prove that the disk image size was the actual issue at our end.

**Comment by aaltat** [comment]
I think we can close this issue.
