### ISSUE TITLE
dependency: rfbrowser init gives: UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-43: character maps to <undefined>

### ISSUE THREAD

**Issue by JoostW21111** [MarketSquare/robotframework-browser#3114]
Bug-Description
When trying to execute
"rfbrowser init"
the following Stacktrace is printed into the console:

2023-09-27 01:04:10,492 [INFO    ] ==============================================================================================================
2023-09-27 01:04:10,492 [INFO    ] Installing node dependencies...
2023-09-27 01:04:20,099 [INFO    ] Installing rfbrowser node dependencies at C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\Browser\wrapper
2023-09-27 01:04:21,033 [INFO    ] npm WARN config production Use `--omit=dev` instead.
2023-09-27 01:05:24,891 [INFO    ] 
2023-09-27 01:05:24,891 [INFO    ] added 61 packages, and audited 62 packages in 1m
2023-09-27 01:05:24,891 [INFO    ] 
2023-09-27 01:05:24,891 [INFO    ] 7 packages are looking for funding
2023-09-27 01:05:24,891 [INFO    ]   run `npm fund` for details
2023-09-27 01:05:24,891 [INFO    ] 
2023-09-27 01:05:24,891 [INFO    ] found 0 vulnerabilities
2023-09-27 01:05:24,906 [INFO    ] 
2023-09-27 01:05:24,906 [INFO    ] 
2023-09-27 01:05:24,906 [INFO    ] 
2023-09-27 01:05:24,906 [INFO    ] 
2023-09-27 01:05:24,906 [INFO    ] Installing browser binaries to C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\Browser\wrapper
2023-09-27 01:05:24,906 [INFO    ] npx --quiet playwright install
2023-09-27 01:05:27,367 [INFO    ] |                                                                                |   0% of 118.6 Mb
--- Logging error ---
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-43: character maps to <undefined>
Call stack:
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\rfbrowser.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\Browser\entry.py", line 321, in init
    _rfbrowser_init(skip_browsers, silent_mode, with_deps, browser)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\Browser\entry.py", line 164, in _rfbrowser_init
    _process_poller(process, silent_mode)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\Browser\entry.py", line 61, in _process_poller
    _log(output, silent_mode)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\Browser\entry.py", line 53, in _log
    logging.info(message.strip("\n"))
Message: '|\u25a0\u25a0\u25a0\u25a0\u25a0\u25a0\u25a0\u25a0                                                                        |  10% of 118.6 Mb'

Reproduction
Establish the following version

Python 3.9.1
pip 23.2.1
robotframework-browser 17.15.1
robotframework  6.1.1
robotframework-assertion-engine 2.0.0
############################## Execution reproduction
run in cmd task in azure pipeline the following dependency
- script: rfbrowser init
  displayName: 'Install dependencies rfbrowser init'

Expected behavior
robotframework setup executes and the appropriate drivers are installed

**Comment by aaltat** [comment]
In which Windows OS and version this happens?

**Comment by JoostW21111** [comment]
that happens in:

Windows 10 Enterprise (64-bits)

**Comment by aaltat** [comment]
And the version is?

**Comment by JoostW21111** [comment]
Correction:

from the build server (Azure) is this:
Windows Server 2022
OS Version: 10.0.20348 
Image Version: 20230918.1.0

Hopefully you have enough information

**Comment by aaltat** [comment]
@allcontributors please add  @JoostW21111 for bugs

**Comment by aaltat** [comment]
Logging the progress bar is difficult in windows. Will suppress the error and continue.

**Comment by rousku** [comment]
I'm witnessing this with robotframework-browser-18.5.1:
```
UnicodeEncodeError: 'charmap' codec can't encode characters in position 36-43: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
```
`rfbrowser init` is run by Azure pipeline agent 3.239.1. Python version is 3.11.9

OS is:

Edition	Windows 10 Pro
Version	22H2
Installed on	‎09/‎11/‎2022
OS build	19045.4412
Experience	Windows Feature Experience Pack 1000.19056.1000.0

**Comment by aaltat** [comment]
Yes, the error happens, but should be only cosmetic thing (but really annoying one.) I think we could detect if the platform is Window (this seems to only happen in Windows) and either just suppress the error or clean the message to contain only ascii.

**Comment by aaltat** [comment]
Moved discussion in #3633
