### ISSUE TITLE
Wait For keyword raise exception for wrong data type

### ISSUE THREAD

**Issue by siongwai** [MarketSquare/robotframework-browser#3922]
**Describe the bug**
Keyword `Wait For    ${promise}` is raised exception.
The exception is: `TypeError: the JSON object must be str, bytes or bytearray, not int`

**To Reproduce**
I have no idea how to reproduce it. I have few test cases which utilise same `Wait For` keyword, but only this test case is failed with exception.

**Screenshots**
![image](https://github.com/user-attachments/assets/40f1594c-9a80-4d00-8713-8fe321f52db0)

log:
```
Traceback (most recent call last):
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\playwright.py", line 170, in grpc_channel
    yield playwright_pb2_grpc.PlaywrightStub(self._channel)
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\keywords\network.py", line 141, in _wait_for_http_response
    return _format_response(response_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\keywords\network.py", line 35, in _format_response
    _jsonize_content(response, "body")
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\keywords\network.py", line 55, in _jsonize_content
    data[bodykey] = json.loads(data[bodykey])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\AppData\Roaming\uv\python\cpython-3.12.7-windows-x86_64-none\Lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\browser.py", line 1241, in run_keyword
    raise e
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\browser.py", line 1230, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\.venv\Lib\site-packages\robotlibcore.py", line 173, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\keywords\promises.py", line 249, in wait_for
    return promises[0].result()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\AppData\Roaming\uv\python\cpython-3.12.7-windows-x86_64-none\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\AppData\Roaming\uv\python\cpython-3.12.7-windows-x86_64-none\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\<dir>\AppData\Roaming\uv\python\cpython-3.12.7-windows-x86_64-none\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\keywords\network.py", line 248, in wait_for_response
    response = self._wait_for_http_response(matcher, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\keywords\network.py", line 126, in _wait_for_http_response
    with self.playwright.grpc_channel() as stub:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<dir>\AppData\Roaming\uv\python\cpython-3.12.7-windows-x86_64-none\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\<dir>\.venv\Lib\site-packages\Browser\playwright.py", line 177, in grpc_channel
    raise AssertionError(str(error))
AssertionError: the JSON object must be str, bytes or bytearray, not int
```

**Additional context**
happen on `19.0.1`

**Comment by aaltat** [comment]
Done in https://github.com/MarketSquare/robotframework-browser/pull/3928
