### ISSUE TITLE
Get Cookie fails if cookie does not have expiry date and return_type=dict. 

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-browser#479]
Get Cookie fails if cookie does not have expiry date and return_type=dict. Example like this: 

![image](https://user-images.githubusercontent.com/2665023/98271758-f290d480-1f98-11eb-8467-6d41ae7d5c25.png)

Keyword should succeed if expiry date does not exist.

**Comment by aaltat** [comment]
Can reproduce in Windows OS only. If I have this test case:
```
Get Cookie And No Expiry
    New Browser    chromium     headless=True
    New Context
    New Page    about:blank
    Add Cookie    tidii    kala    http://address.com/to/site
    ${cookie} =    Get Cookie    tidii    return_type=dict
    Log    ${cookie}
```
Then there is this error:
```
Traceback (most recent call last):
  File "d:\workspace\.venv\lib\site-packages\Browser\browser.py", line 680, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "d:\workspace\.venv\lib\site-packages\robotlibcore.py", line 103, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "d:\workspace\.venv\lib\site-packages\Browser\keywords\cookie.py", line 205, in get_cookie
    return self._cookie_as_dot_dict(cookie_dict)
  File "d:\workspace\.venv\lib\site-packages\Browser\keywords\cookie.py", line 79, in _cookie_as_dot_dict
    dot_dict[key] = datetime.fromtimestamp(cookie[key])
```
Added logging and expiry value is `-1`. I guess the way to fix it suppress the exception and log it.
