### ISSUE TITLE
rfbrowser init fails for version 0.2.0

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#52]
```
Installing collected packages: robotframework-pythonlibcore, robotframework-browser
  Attempting uninstall: robotframework-browser
    Found existing installation: robotframework-browser 0.1.0
    Uninstalling robotframework-browser-0.1.0:
      Successfully uninstalled robotframework-browser-0.1.0
Successfully installed robotframework-browser-0.2.0 robotframework-pythonlibcore-2.0.2
➜  rfbrowser init
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/rfbrowser", line 5, in <module>
    from Browser.entry import run
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Browser/__init__.py", line 10, in <module>
    from .keywords import Validation, Control, Input
ModuleNotFoundError: No module named 'Browser.keywords'
```

**Comment by xylix** [comment]
Got through this, but now we have the problem ``` ==============================================================================
Checkbox Should Be Checked                                            | FAIL |
Setup failed:
Could not connect to the playwright process at port 55957``` (see for example https://github.com/MarketSquare/robotframework-browser/runs/807134799 )
