### ISSUE TITLE
Segmentation fault: 11 installing on Mac OS X 10.15.7

### ISSUE THREAD

**Issue by damies13** [MarketSquare/robotframework-browser#531]
**Describe the bug**
I tried to follow the installation instructions but the rfbrowser init step produces a Segmentation fault

rfbrowser init
"Segmentation fault: 11"

Additionally running robot with a test case that uses Library Browser or typing import Browser at the python prompt will also produce the same segmentation fault.

Hopefully I have provided enough information below to know what the issue is? If not or you need me to gather additional information please ask.

**To Reproduce**
```
DavesMBP:~ dave$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
DavesMBP:~ dave$ node -v
v14.15.1
DavesMBP:~ dave$ sudo pip3 install robotframework-browser
Password:
WARNING: The directory '/Users/dave/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/dave/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: robotframework-browser in /usr/local/lib/python3.7/site-packages (2.3.2)
Requirement already satisfied: grpcio<2.0.0,>=1.33.1 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (1.34.0)
Requirement already satisfied: grpcio-tools<2.0.0,>=1.33.1 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (1.34.0)
Requirement already satisfied: backports.cached-property>=1.0.0 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (1.0.0.post2)
Requirement already satisfied: wrapt>=1.12.1 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (1.12.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (3.7.4.3)
Requirement already satisfied: robotframework>=3.2.2 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (3.2.2)
Requirement already satisfied: robotframework-pythonlibcore>=2.1.0 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (2.1.0)
Requirement already satisfied: six>=1.5.2 in ./Library/Python/3.7/lib/python/site-packages (from grpcio<2.0.0,>=1.33.1->robotframework-browser) (1.12.0)
Requirement already satisfied: setuptools in ./Library/Python/3.7/lib/python/site-packages (from grpcio-tools<2.0.0,>=1.33.1->robotframework-browser) (50.3.2)
Requirement already satisfied: protobuf<4.0dev,>=3.5.0.post1 in /usr/local/lib/python3.7/site-packages (from grpcio-tools<2.0.0,>=1.33.1->robotframework-browser) (3.14.0)
DavesMBP:~ dave$ rfbrowser init
Segmentation fault: 11
```

**Expected behavior**
[Installation instructions](https://github.com/MarketSquare/robotframework-browser#installation-instructions) do not state what the expected output of rfbrowser init is but I suspect it is not Segmentation fault: 11

Expected to be able to run the [example test case](https://github.com/MarketSquare/robotframework-browser#testing-with-robot-framework)

**Screenshots**
See To Reproduce for console log

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Version 10.15.7
 - Browser: not applicable didn't get that far

**Comment by damies13** [comment]
After posting this issue I thought what if rfbrowser init requires elevated permissions, so I tried:
```
DavesMBP:~ dave$ sudo rfbrowser init
Password:
Segmentation fault: 11
```

**Comment by xylix** [comment]
Could you try to either use a virtual environment or install with 
```
sudo pip3 uninstall robotframework-browser
pip3 install --user robotframework-browser
rfbrowser init
```
? Trying to catch what exactly is causing this issue... current best guess is that it's related to permissions at rfbrowser init time

**Comment by Pranjilagrawal** [comment]
I’m getting the same issue.
Installing in mac os x 10.15.7
Python version 3.8
tried using both:
sudo pip3 install robotframework-browser 
or
pip3 install robotframework-browser
and when I’m trying    rfbrowser init
i'm getting this:  zsh: segmentation fault  rfbrowser init

**Comment by xylix** [comment]
Can you please test the just released 2.3.3?
```
pip install --upgrade robotframework-browser
rfbrowser init
```
It should have a fix for this.

**Comment by damies13** [comment]
> Could you try to either use a virtual environment or install with
> 
> ```
> sudo pip3 uninstall robotframework-browser
> pip3 install --user robotframework-browser
> rfbrowser init
> ```

```
DavesMBP:~ dave$ sudo pip3 uninstall robotframework-browser
Password:
WARNING: The directory '/Users/dave/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling robotframework-browser-2.3.2:
  Would remove:
    /usr/local/bin/rfbrowser
    /usr/local/lib/python3.7/site-packages/Browser/*
    /usr/local/lib/python3.7/site-packages/robotframework_browser-2.3.2.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled robotframework-browser-2.3.2
DavesMBP:~ dave$ pip3 install --user robotframework-browser
Collecting robotframework-browser
  Downloading https://files.pythonhosted.org/packages/7a/3b/8cae03879b51673055ea72477eae62d03b34f49690d801e69507210d56f6/robotframework_browser-2.3.3-py3-none-any.whl (1.8MB)
     |████████████████████████████████| 1.8MB 5.2MB/s 
Requirement already satisfied: wrapt>=1.12.1 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (1.12.1)
Requirement already satisfied: protobuf==3.14.0 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (3.14.0)
Collecting grpcio-tools==1.33.1 (from robotframework-browser)
  Downloading https://files.pythonhosted.org/packages/6a/c3/e5af845314af2d969266f6ec6c6c27e7ded00d561f5797246a3f889fc273/grpcio_tools-1.33.1-cp37-cp37m-macosx_10_9_x86_64.whl (2.0MB)
     |████████████████████████████████| 2.0MB 8.2MB/s 
Requirement already satisfied: robotframework-pythonlibcore>=2.1.0 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (2.1.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (3.7.4.3)
Collecting grpcio==1.33.1 (from robotframework-browser)
  Downloading https://files.pythonhosted.org/packages/82/64/e60c54e401ae5e7c690f689c893a00e82ce85679588c7836ff90804f7108/grpcio-1.33.1-cp37-cp37m-macosx_10_9_x86_64.whl (3.4MB)
     |████████████████████████████████| 3.4MB 8.0MB/s 
Requirement already satisfied: backports.cached-property>=1.0.0 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (1.0.0.post2)
Requirement already satisfied: robotframework>=3.2.2 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (3.2.2)
Requirement already satisfied: six>=1.9 in ./Library/Python/3.7/lib/python/site-packages (from protobuf==3.14.0->robotframework-browser) (1.12.0)
Installing collected packages: grpcio, grpcio-tools, robotframework-browser
  WARNING: The script rfbrowser is installed in '/Users/dave/Library/Python/3.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed grpcio-1.33.1 grpcio-tools-1.33.1 robotframework-browser-2.3.3
DavesMBP:~ dave$ rfbrowser init
-bash: /usr/local/bin/rfbrowser: No such file or directory
DavesMBP:~ dave$ 
```
Hmmm No such file or directory, not in the path I guess...

```

DavesMBP:~ dave$ ./Library/Python/3.7/bin/rfbrowser init
Installing node dependencies...
Installing rfbrowser node dependencies at /Users/dave/Library/Python/3.7/lib/python/site-packages/Browser/wrapper


> playwright@1.6.2 install /Users/dave/Library/Python/3.7/lib/python/site-packages/Browser/wrapper/node_modules/playwright

> node install.js





chromium v827102 downloaded to /Users/dave/Library/Python/3.7/lib/python/site-packages/Browser/wrapper/node_modules/playwright/.local-browsers/chromium-827102



firefox v1205 downloaded to /Users/dave/Library/Python/3.7/lib/python/site-packages/Browser/wrapper/node_modules/playwright/.local-browsers/firefox-1205



webkit v1383 downloaded to /Users/dave/Library/Python/3.7/lib/python/site-packages/Browser/wrapper/node_modules/playwright/.local-browsers/webkit-1383

npm WARN robotframework-playwright@2.3.3 No description

npm WARN robotframework-playwright@2.3.3 No repository field.



added 65 packages from 109 contributors and audited 985 packages in 64.429s



5 packages are looking for funding

  run `npm fund` for details



found 0 vulnerabilities




rfbrowser init completed
DavesMBP:~ dave$ 

```

That looks better...

> 
> ? Trying to catch what exactly is causing this issue... current best guess is that it's related to permissions at rfbrowser init time

Can you tell me how I can catch "exactly is causing this issue", I tried running `robot --console verbose` hoping to get more detail but still got the same message.


[Browser_Example.robot](https://github.com/MarketSquare/robotframework-browser#testing-with-robot-framework) is the example from the readme verbatim.
```
DavesMBP:Regression_Tests dave$ robot Browser_Example.robot 
==============================================================================
Browser Example                                                               
==============================================================================
Example Test                                                          | PASS |
------------------------------------------------------------------------------
Browser Example                                                       | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  /Users/dave/Documents/GitHub/TestDataTable/Regression_Tests/output.xml
Log:     /Users/dave/Documents/GitHub/TestDataTable/Regression_Tests/log.html
Report:  /Users/dave/Documents/GitHub/TestDataTable/Regression_Tests/report.html
DavesMBP:Regression_Tests dave$ 

```

Looks like it's working for current user, but no idea why not for all users, I guess it's a permissions thing.

**Comment by xylix** [comment]
@damies13 I think the update 2.3.3 we just got out could have fixed it for you. I recommend trying your previous non-working attempt again with the newer version to confirm if it works.

RFBrowser not being found after `--user` install is probably related to local systems PATH configuration... But thanks for trying out the examples!

**Comment by Pranjilagrawal** [comment]
version 2.3.3 successfully installed but getting this after doing rfbrowser init

rfbrowser init                                 
Installing node dependencies...
Installing rfbrowser node dependencies at /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Browser/wrapper
npm WARN checkPermissions Missing write access to /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Browser/wrapper

npm WARN robotframework-playwright@2.3.3 No description

npm WARN robotframework-playwright@2.3.3 No repository field.



npm ERR! code EACCES

npm ERR! syscall access

npm ERR! path /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Browser/wrapper

npm ERR! errno -13

npm ERR! Error: EACCES: permission denied, access '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Browser/wrapper'

npm ERR!  [Error: EACCES: permission denied, access '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Browser/wrapper'] {

npm ERR!   errno: -13,

npm ERR!   code: 'EACCES',

npm ERR!   syscall: 'access',

npm ERR!   path: '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Browser/wrapper'

npm ERR! }

npm ERR! 

npm ERR! The operation was rejected by your operating system.

npm ERR! It is likely you do not have the permissions to access this file as the current user

npm ERR! 

npm ERR! If you believe this might be a permissions issue, please double-check the

npm ERR! permissions of the file and its containing directories, or try running

npm ERR! the command again as root/Administrator.



npm ERR! A complete log of this run can be found in:

npm ERR!     /Users/pranjilagrawal/.npm/_logs/2020-12-03T13_53_13_255Z-debug.log


Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/rfbrowser", line 8, in <module>
    sys.exit(run())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Browser/entry.py", line 39, in run
    rfbrowser_init(arg2 == "--skip-browsers")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/Browser/entry.py", line 97, in rfbrowser_init
    raise RuntimeError(
RuntimeError: Problem installing node dependencies.Node process returned with exit status 243

**Comment by xylix** [comment]
Okay yeah. This last error is a case of the directory where the pip package is installed not being writable by `rfbrowser init`. Running `sudo rfbrowser init` could work, but then the files might not be correctly accessible at run time.

**Comment by Pranjilagrawal** [comment]
i tried this:
sudo pip3 uninstall robotframework-browser
pip3 install --user robotframework-browser

rfbrowser init
But getting error :zsh: command not found: rfbrowser

**Comment by xylix** [comment]
Try
`~/Library/Python/3.8/bin/rfbrowser init` (or equivalent, look where the --user installs the package)

**Comment by damies13** [comment]
Ok this morning tried this:
`pip3 uninstall --user robotframework-browser`
oops errored, remove --user

```
DavesMBP:~ dave$ sudo pip3 install robotframework-browser
Password:
WARNING: The directory '/Users/dave/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/dave/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting robotframework-browser
  Downloading https://files.pythonhosted.org/packages/7a/3b/8cae03879b51673055ea72477eae62d03b34f49690d801e69507210d56f6/robotframework_browser-2.3.3-py3-none-any.whl (1.8MB)
     |████████████████████████████████| 1.8MB 3.1MB/s 
Requirement already satisfied: protobuf==3.14.0 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (3.14.0)
Requirement already satisfied: backports.cached-property>=1.0.0 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (1.0.0.post2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (3.7.4.3)
Requirement already satisfied: robotframework-pythonlibcore>=2.1.0 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (2.1.0)
Requirement already satisfied: grpcio==1.33.1 in ./Library/Python/3.7/lib/python/site-packages (from robotframework-browser) (1.33.1)
Requirement already satisfied: robotframework>=3.2.2 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (3.2.2)
Requirement already satisfied: grpcio-tools==1.33.1 in ./Library/Python/3.7/lib/python/site-packages (from robotframework-browser) (1.33.1)
Requirement already satisfied: wrapt>=1.12.1 in /usr/local/lib/python3.7/site-packages (from robotframework-browser) (1.12.1)
Requirement already satisfied: six>=1.9 in ./Library/Python/3.7/lib/python/site-packages (from protobuf==3.14.0->robotframework-browser) (1.12.0)
Installing collected packages: robotframework-browser
Successfully installed robotframework-browser-2.3.3
DavesMBP:~ dave$ sudo rfbrowser init
Installing node dependencies...
Installing rfbrowser node dependencies at /usr/local/lib/python3.7/site-packages/Browser/wrapper


> playwright@1.6.2 install /usr/local/lib/python3.7/site-packages/Browser/wrapper/node_modules/playwright

> node install.js



(node:35758) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir '/usr/local/lib/python3.7/site-packages/Browser/wrapper/node_modules/playwright/.local-browsers'

(Use `node --trace-warnings ...` to show where the warning was created)

(node:35758) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:35758) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

npm WARN robotframework-playwright@2.3.3 No description

npm WARN robotframework-playwright@2.3.3 No repository field.



added 65 packages from 109 contributors and audited 985 packages in 2.864s



5 packages are looking for funding

  run `npm fund` for details



found 0 vulnerabilities




rfbrowser init completed
DavesMBP:~ dave$ 
```

Ok that looks like it's fixed, one final check
```
DavesMBP:Regression_Tests dave$ robot Browser_Example.robot 
==============================================================================
Browser Example                                                               
==============================================================================
[ WARN ] Keyword 'Take Screenshot' could not be run on failure:               
Error: Tried to take screenshot, but no page was open.
Example Test                                                          | FAIL |
Error: browserType.launch: Failed to launch chromium because executable doesn't exist at /usr/local/lib/python3.7/site-packages/Browser/wrapper/node_modules/playwright/.local-browsers/chromium-827102/chrome-mac/Chromium.app/Contents/MacOS/Chromium
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
------------------------------------------------------------------------------
Browser Example                                                       | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /Users/dave/Documents/GitHub/TestDataTable/Regression_Tests/output.xml
Log:     /Users/dave/Documents/GitHub/TestDataTable/Regression_Tests/log.html
Report:  /Users/dave/Documents/GitHub/TestDataTable/Regression_Tests/report.html
```

Hmmm ok lets try:
```
DavesMBP:~ dave$ sudo npm install playwright

> playwright@1.6.2 install /Users/dave/node_modules/playwright
> node install.js

Downloading chromium v827102 - 121.3 Mb [====================] 100% 0.0s 
chromium v827102 downloaded to /Users/dave/Library/Caches/ms-playwright/chromium-827102
Downloading firefox v1205 - 74.1 Mb [====================] 100% 0.0s 
firefox v1205 downloaded to /Users/dave/Library/Caches/ms-playwright/firefox-1205
Downloading webkit v1383 - 49.8 Mb [====================] 100% 0.0s 
webkit v1383 downloaded to /Users/dave/Library/Caches/ms-playwright/webkit-1383
npm WARN saveError ENOENT: no such file or directory, open '/Users/dave/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/dave/package.json'
npm WARN dave No description
npm WARN dave No repository field.
npm WARN dave No README data
npm WARN dave No license field.

+ playwright@1.6.2
added 37 packages from 83 contributors and audited 37 packages in 65.86s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```
DavesMBP:Regression_Tests dave$ robot Browser_Example.robot 
==============================================================================
Browser Example                                                               
==============================================================================
[ WARN ] Keyword 'Take Screenshot' could not be run on failure:               
Error: Tried to take screenshot, but no page was open.
Example Test                                                          | FAIL |
Error: browserType.launch: Failed to launch chromium because executable doesn't exist at /usr/local/lib/python3.7/site-packages/Browser/wrapper/node_modules/playwright/.local-browsers/chromium-827102/chrome-mac/Chromium.app/Contents/MacOS/Chromium
Try re-installing playwright with "npm install playwright"
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
------------------------------------------------------------------------------
Browser Example                                                       | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /Users/dave/Documents/GitHub/TestDataTable/Regression_Tests/output.xml
Log:     /Users/dave/Documents/GitHub/TestDataTable/Regression_Tests/log.html
Report:  /Users/dave/Documents/GitHub/TestDataTable/Regression_Tests/report.html
DavesMBP:Regression_Tests dave$ 
```
No that didn't work either

**Comment by damies13** [comment]
I fear my machine is in a bit of a messed up state now, is there a command I can run that will uninstall everything that gets installed by:
```
pip install robotframework-browser
rfbrowser init
```

**Comment by damies13** [comment]
I think I found the problem, sudo npm install playwright installed chromium to: 
`/Users/dave/Library/Caches/ms-playwright/chromium-827102`

Interesting that sudo npm still installed in my user profile.

But Browser is looking for it here:
`/usr/local/lib/python3.7/site-packages/Browser/wrapper/node_modules/playwright/.local-browsers/chromium-827102/chrome-mac/Chromium.app/Contents/MacOS/Chromium`

I checked `/usr/local/lib/python3.7/site-packages/Browser/wrapper/node_modules/playwright/.local-browsers/` doesn't exist on my machine, but `/usr/local/lib/python3.7/site-packages/Browser/wrapper/node_modules/playwright/` does

**Comment by damies13** [comment]
Ok was able to reset and get things working again with
```
sudo pip3 uninstall robotframework-browser
pip3 install --user robotframework-browser
./Library/Python/3.7/bin/rfbrowser init
```

**Comment by xylix** [comment]
Yeah the `npm install playwright` recommendation comes from the underlying playwright library, and when that command is run, Playwright then installs browsers into it's own default location instead of the one used by `robotframework-browser`.

To help with future issues like this, we implemented a permission check at `rfbrowser init` which will give a more helpful error if the problem is that rfbrowser init can't write into the directory.

Grea that you got it working at last! If you don't have any more direct problems we could close this issue and then re-open if the problem pops up again.

**Comment by damies13** [comment]
Yeah I got it working, but if the way I got it working is the solution then you probably need to keep this open at least until the install instructions are updated.
I doubt many people would be able to figure out how to get this working the way I did.

**Comment by xylix** [comment]
Good point. Added running `python3 -m Browser.entry init` as alternative to `rfbrowser init` when the library is installed in the python environment but `rfbrowser` is not found in the path e84abd9317e1ae83877836597b72bfb94a40004d
