### ISSUE TITLE
robotframework-browser initialisation (rfbrowser init) fails on macOS 11.1

### ISSUE THREAD

**Issue by xuyang61** [MarketSquare/robotframework-browser#598]
**Describe the bug**

`rfbrowser init` fails on macOS 11.1, "Playwright does not support chromium on mac11.1" (this is fixed on playwright 1.7.0, but robotframework-browser uses 1.6.2). It is not obvious how to work around the problem.

**To Reproduce**

```
user ~ % sw_vers
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
user ~ % node --version
v14.15.3
user ~ % pip install robotframework-browser
Collecting robotframework-browser
  Downloading robotframework_browser-2.4.0-py3-none-any.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 4.7 MB/s
Requirement already satisfied: backports.cached-property>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from robotframework-browser) (1.0.0.post2)
Requirement already satisfied: grpcio==1.33.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from robotframework-browser) (1.33.2)
Requirement already satisfied: robotframework>=3.2.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from robotframework-browser) (3.2.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from robotframework-browser) (3.7.4.3)
Requirement already satisfied: grpcio-tools==1.33.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from robotframework-browser) (1.33.2)
Requirement already satisfied: robotframework-pythonlibcore>=2.1.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from robotframework-browser) (2.1.0)
Requirement already satisfied: protobuf==3.14.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from robotframework-browser) (3.14.0)
Requirement already satisfied: wrapt>=1.12.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from robotframework-browser) (1.12.1)
Requirement already satisfied: six>=1.5.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from grpcio==1.33.2->robotframework-browser) (1.15.0)
Installing collected packages: robotframework-browser
Successfully installed robotframework-browser-2.4.0
yangxu@Yangs-MacBook-Pro ~ % rfbrowser init
Installing node dependencies...
Installing rfbrowser node dependencies at /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper
npm WARN deprecated highlight.js@9.18.5: Support has ended for 9.x series. Upgrade to @latest

npm WARN deprecated gulp-header@1.8.12: Removed event-stream from gulp-header

npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated

npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated



> playwright@1.6.2 install /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/node_modules/playwright

> node install.js



(node:8462) UnhandledPromiseRejectionWarning: Error: ERROR: Playwright does not support chromium on mac11.1

    at Object.assert (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/node_modules/playwright/lib/utils/utils.js:58:15)

    at revisionURL (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/node_modules/playwright/lib/install/browserFetcher.js:131:13)

    at Object.downloadBrowserWithProgressBar (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/node_modules/playwright/lib/install/browserFetcher.js:156:17)

    at async validateCache (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/node_modules/playwright/lib/install/installer.js:99:9)

    at async installBrowsersWithProgressBar (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/node_modules/playwright/lib/install/installer.js:56:5)

(Use `node --trace-warnings ...` to show where the warning was created)

(node:8462) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:8462) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

npm WARN @typescript-eslint/eslint-plugin@4.10.0 requires a peer of @typescript-eslint/parser@^4.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN robotframework-playwright@2.4.0 No description

npm WARN robotframework-playwright@2.4.0 No repository field.



added 65 packages from 109 contributors and audited 873 packages in 5.922s



5 packages are looking for funding

  run `npm fund` for details



found 1 low severity vulnerability

  run `npm audit fix` to fix them, or `npm audit` for details


rfbrowser init completed
user ~ %
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 11.1

**Comment by aaltat** [comment]
If I recall correctly this is upstream issue, more details in here: https://github.com/microsoft/playwright/issues/4722

**Comment by xuyang61** [comment]
> playwright@1.6.2 install /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper/node_modules/playwright

> node install.js

This needs to be upgraded on robotframework-browser then?

I tried to hack around this problem on basis of https://github.com/microsoft/playwright/issues/4722 but didn't immediately succeed at it...

**Comment by xylix** [comment]
Fixed in 2.4.2. Coming out to pypi within 20 minutes.

**Comment by xylix** [comment]
2.4.2 out and released, fixes this. Please re-open if the fix doesn't work

**Comment by xuyang61** [comment]
Thanks for the quick release. at least some problems are solved :)
